apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: serp-sail-trino
  namespace: hiru-mgmt-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: serp-sail-trino
  destination:
    server: https://kubernetes.default.svc
    namespace: serp-sail-trino
  syncPolicy:
    automated: 
      selfHeal: true 
    syncOptions: 
    - CreateNamespace=true 
  source:
    repoURL: git@github.com/tekkisse/testk8s
    targetRevision: HEAD
    path: trino/apps
    
