apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: minio-env-config-secret
  namespace: serp-sail-trino
spec:
  refreshPeriod: 72h0m0s
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: sail
        serviceAccount:
          name: default
      name: minio
      path: kvv2/data/prod/sail/trino/minio
  output:
    name: minio-env-config
    stringData:
      access_key: {{`'{{ .minio.access_key }}'`}}
      secret_key: {{`'{{ .minio.secret_key }}'`}}
      config.env: |
        export MINIO_ROOT_USER="{{`{{ .minio.access_key }}`}}" 
        export MINIO_ROOT_PASSWORD="{{`{{ .minio.secret_key }}`}}"
        export MINIO_IDENTITY_OPENID_CLIENT_ID_PRIMARY_IAM="{{`{{ .minio.keycloak_client_id }}`}}"
        export MINIO_IDENTITY_OPENID_CLIENT_SECRET_PRIMARY_IAM="{{`{{ .minio.keycloak_client_secret }}`}}"
    type: Opaque

---

apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: hive-postgres-secret
  namespace: serp-sail-trino
spec:
  refreshPeriod: 72h0m0s
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: sail
        serviceAccount:
          name: default
      name: pg_secret
      path: kvv2/data/prod/sail/trino/postgres
  output:
    name: hive-postgres-secret
    stringData:
      username: {{`'{{ .pg_secret.postgres_hive_username }}'`}}
      password: {{`'{{ .pg_secret.postgres_hive_password }}'`}}
    type: Opaque

